-- Honest starter content for RIT. Safe to re-run after schema.sql.
insert into public.projects(slug,title_en,title_bn,summary_en,summary_bn,status,published,featured,sort_order,category,year,technologies,objectives_en,results_en) values
('batch-type-grain-dryer','Batch Type Grain Dryer','ব্যাচ টাইপ গ্রেইন ড্রায়ার','Reliable batch drying concept intended to support better grain quality.','উন্নত শস্যমানের জন্য নির্ভরযোগ্য ব্যাচ শুকানোর ধারণা।','prototype',true,true,1,'Agro Engineering',2026,array['Engineering design','Prototyping'],'Develop a practical, maintainable grain drying solution.','Development is ongoing; verified results will be published when available.'),
('vacuum-paddy-collector','Vacuum Paddy Collector','ভ্যাকুয়াম ধান সংগ্রাহক','Efficient paddy collection concept with reduced manual handling.','কম শ্রমে দক্ষভাবে ধান সংগ্রহের ধারণা।','development',true,true,2,'Agro Engineering',2026,array['Engineering design','Prototyping'],'Develop a practical paddy collection system.','Development is ongoing.'),
('mobile-paddy-parboiling','Mobile Paddy Parboiling','মোবাইল ধান পারবয়েলিং','A flexible concept for mobile paddy processing.','মোবাইল ধান প্রক্রিয়াজাতকরণের একটি নমনীয় ধারণা।','research',true,false,3,'Agro Engineering',2026,array['Research','Engineering design'],'Explore mobile parboiling requirements.','Research is ongoing.'),
('smart-seed-system','Smart Seed System','স্মার্ট বীজ ব্যবস্থা','Precision tools for more confident seed management.','উন্নত বীজ ব্যবস্থাপনার জন্য নির্ভুল সরঞ্জামের ধারণা।','concept',true,false,4,'Smart Farming',2026,array['Product design','Smart farming'],'Document a practical seed management workflow.','Concept development is ongoing.'),
('grain-stirring-system','Grain Stirring System','শস্য নাড়াচাড়া ব্যবস্থা','Consistent airflow and grain management during drying.','শুকানোর সময় সমান বায়ুপ্রবাহ ও শস্য ব্যবস্থাপনার ধারণা।','prototype',true,false,5,'Agro Engineering',2026,array['Mechanical design','Prototyping'],'Improve consistency during grain drying.','Prototype work is ongoing.'),
('cnc-engineering','CNC Engineering','সিএনসি ইঞ্জিনিয়ারিং','Precision fabrication concepts for future-ready components.','নির্ভুল যন্ত্রাংশ তৈরির প্রকৌশল ধারণা।','active',true,false,6,'Engineering',2026,array['CNC','Fabrication'],'Develop accurate and maintainable fabrication workflows.','Capabilities are being developed.')
on conflict(slug) do update set title_en=excluded.title_en,title_bn=excluded.title_bn,summary_en=excluded.summary_en,summary_bn=excluded.summary_bn,status=excluded.status,published=excluded.published,featured=excluded.featured,sort_order=excluded.sort_order,category=excluded.category,year=excluded.year,technologies=excluded.technologies,objectives_en=excluded.objectives_en,results_en=excluded.results_en;

insert into public.apps(slug,title_en,title_bn,summary_en,summary_bn,status,published,featured,sort_order,platform) values
('hisab-khata','Hisab Khata','হিসাব খাতা','A focused bookkeeping application designed for simple local workflows.','সহজ স্থানীয় হিসাব ব্যবস্থাপনার জন্য একটি অ্যাপ।','development',true,true,1,'Android'),
('krishi-bondhu','Krishi Bondhu','কৃষি বন্ধু','A practical agriculture-focused digital product in development.','কৃষিকেন্দ্রিক একটি ব্যবহারিক ডিজিটাল পণ্য।','development',true,true,2,'Android'),
('banglabook','BanglaBook','বাংলাবুক','A Bangla-focused digital reading product in development.','বাংলা পাঠের জন্য একটি ডিজিটাল পণ্য।','development',true,false,3,'Android'),
('nurani-shishu','Nurani Shishu','নূরানী শিশু','A child-focused learning application in development.','শিশুদের জন্য একটি শিক্ষামূলক অ্যাপ।','development',true,false,4,'Android'),
('nursery-1','Nursery-1','নার্সারি-১','An early-learning application in development.','প্রাথমিক শিক্ষার একটি অ্যাপ।','development',true,false,5,'Android'),
('deen-islam','Deen Islam','দ্বীন ইসলাম','An Islamic information application in development.','ইসলামিক তথ্যভিত্তিক একটি অ্যাপ।','development',true,false,6,'Android')
on conflict(slug) do update set title_en=excluded.title_en,title_bn=excluded.title_bn,summary_en=excluded.summary_en,summary_bn=excluded.summary_bn,status=excluded.status,published=excluded.published,featured=excluded.featured,sort_order=excluded.sort_order,platform=excluded.platform;

insert into public.founder_profiles(slug,title_en,title_bn,summary_en,summary_bn,role_en,role_bn,philosophy_en,philosophy_bn,expertise,status,published,featured) values
('md-rasel-ahmed','Md. Rasel Ahmed','মো. রাসেল আহমেদ','Founder of Rasel Innovation & Technology.','রাসেল ইনোভেশন অ্যান্ড টেকনোলজির প্রতিষ্ঠাতা।','Founder','প্রতিষ্ঠাতা','Practical ideas, carefully developed, can create meaningful progress.','সযত্নে গড়া বাস্তব ধারণা অর্থবহ অগ্রগতি তৈরি করতে পারে।',array['Agricultural innovation','Engineering concepts','Digital products'],'active',true,true)
on conflict(slug) do update set title_en=excluded.title_en,title_bn=excluded.title_bn,summary_en=excluded.summary_en,summary_bn=excluded.summary_bn,role_en=excluded.role_en,role_bn=excluded.role_bn,philosophy_en=excluded.philosophy_en,philosophy_bn=excluded.philosophy_bn,expertise=excluded.expertise,published=excluded.published;

insert into public.achievements(slug,title_en,title_bn,summary_en,summary_bn,year,status,published,sort_order) values
('website-launched','RIT website launched','RIT ওয়েবসাইট চালু','The public RIT website and content structure were launched.','RIT-এর জনসাধারণের ওয়েবসাইট ও কনটেন্ট কাঠামো চালু হয়েছে।',2026,'active',true,1),
('research-portfolio-organized','Research portfolio organized','গবেষণা পোর্টফোলিও সংগঠিত','RIT research concepts were organized for transparent presentation.','RIT-এর গবেষণা ধারণাগুলো স্বচ্ছভাবে উপস্থাপনের জন্য সংগঠিত হয়েছে।',2026,'active',true,2),
('application-development-expanded','Application development expanded','অ্যাপ উন্নয়ন সম্প্রসারিত','The published application portfolio was expanded.','প্রকাশিত অ্যাপ পোর্টফোলিও সম্প্রসারিত হয়েছে।',2026,'active',true,3),
('engineering-concepts-documented','Engineering concepts documented','প্রকৌশল ধারণা নথিভুক্ত','Agricultural engineering concepts were documented for continued development.','কৃষি প্রকৌশল ধারণাগুলো ভবিষ্যৎ উন্নয়নের জন্য নথিভুক্ত হয়েছে।',2026,'active',true,4)
on conflict(slug) do update set title_en=excluded.title_en,title_bn=excluded.title_bn,summary_en=excluded.summary_en,summary_bn=excluded.summary_bn,year=excluded.year,published=excluded.published,sort_order=excluded.sort_order;

insert into public.timeline_events(slug,title_en,title_bn,summary_en,summary_bn,event_date,year,status,published,sort_order)
select slug,title_en,title_bn,summary_en,summary_bn,make_date(year,least(sort_order+3,12),1),year,'active',true,sort_order from public.achievements where slug in('website-launched','research-portfolio-organized','application-development-expanded','engineering-concepts-documented')
on conflict(slug) do update set title_en=excluded.title_en,title_bn=excluded.title_bn,summary_en=excluded.summary_en,summary_bn=excluded.summary_bn,event_date=excluded.event_date,published=excluded.published,sort_order=excluded.sort_order;

insert into public.news_articles(slug,title_en,title_bn,summary_en,summary_bn,author,published_at,category,status,published,featured,sort_order) values
('corporate-website-launched','RIT launches its renewed corporate website','RIT-এর নতুন কর্পোরেট ওয়েবসাইট চালু','The renewed website organizes RIT projects, applications and published updates.','নতুন ওয়েবসাইটে RIT-এর প্রকল্প, অ্যাপ ও প্রকাশিত আপডেট সংগঠিত হয়েছে।','RIT Editorial','2026-07-18','Company update','published',true,true,1),
('agricultural-concepts-prototyping','Agricultural concepts move into prototyping','কৃষি ধারণার প্রোটোটাইপ উন্নয়ন','Selected published agricultural concepts are being organized for prototyping.','নির্বাচিত কৃষি ধারণাগুলো প্রোটোটাইপ উন্নয়নের জন্য সংগঠিত হচ্ছে।','RIT Editorial','2026-07-17','Innovation','published',true,false,2),
('digital-learning-portfolio','RIT Apps expands its digital learning portfolio','RIT Apps-এর ডিজিটাল শিক্ষা পোর্টফোলিও সম্প্রসারণ','RIT Apps has organized additional published learning-product concepts.','RIT Apps আরও প্রকাশিত শিক্ষা-পণ্যের ধারণা সংগঠিত করেছে।','RIT Editorial','2026-07-16','Products','published',true,false,3)
on conflict(slug) do update set title_en=excluded.title_en,title_bn=excluded.title_bn,summary_en=excluded.summary_en,summary_bn=excluded.summary_bn,author=excluded.author,published_at=excluded.published_at,category=excluded.category,published=excluded.published,featured=excluded.featured,sort_order=excluded.sort_order;

insert into public.gallery_items(slug,title_en,title_bn,summary_en,summary_bn,alt_en,alt_bn,caption_en,caption_bn,category,status,published,sort_order) values
('field-innovation','Field innovation','মাঠ পর্যায়ের উদ্ভাবন','Image placeholder awaiting an owner-provided photo.','মালিকের ছবি যোগ করার অপেক্ষায় প্লেসহোল্ডার।','Field innovation placeholder','মাঠ পর্যায়ের উদ্ভাবনের প্লেসহোল্ডার','Photo coming soon','ছবি শিগগিরই যোগ হবে','Agriculture','placeholder',true,1),
('engineering-studio','Engineering studio','প্রকৌশল স্টুডিও','Image placeholder awaiting an owner-provided photo.','মালিকের ছবি যোগ করার অপেক্ষায় প্লেসহোল্ডার।','Engineering studio placeholder','প্রকৌশল স্টুডিও প্লেসহোল্ডার','Photo coming soon','ছবি শিগগিরই যোগ হবে','Engineering','placeholder',true,2),
('product-thinking','Product thinking','পণ্য পরিকল্পনা','Image placeholder awaiting an owner-provided photo.','মালিকের ছবি যোগ করার অপেক্ষায় প্লেসহোল্ডার।','Product thinking placeholder','পণ্য পরিকল্পনার প্লেসহোল্ডার','Photo coming soon','ছবি শিগগিরই যোগ হবে','Digital','placeholder',true,3),
('applied-research','Applied research','প্রয়োগমূলক গবেষণা','Image placeholder awaiting an owner-provided photo.','মালিকের ছবি যোগ করার অপেক্ষায় প্লেসহোল্ডার।','Applied research placeholder','প্রয়োগমূলক গবেষণার প্লেসহোল্ডার','Photo coming soon','ছবি শিগগিরই যোগ হবে','Research','placeholder',true,4),
('digital-tools','Digital tools','ডিজিটাল টুলস','Image placeholder awaiting an owner-provided photo.','মালিকের ছবি যোগ করার অপেক্ষায় প্লেসহোল্ডার।','Digital tools placeholder','ডিজিটাল টুলস প্লেসহোল্ডার','Photo coming soon','ছবি শিগগিরই যোগ হবে','Digital','placeholder',true,5),
('growing-ideas','Growing ideas','বিকাশমান ধারণা','Image placeholder awaiting an owner-provided photo.','মালিকের ছবি যোগ করার অপেক্ষায় প্লেসহোল্ডার।','Growing ideas placeholder','বিকাশমান ধারণার প্লেসহোল্ডার','Photo coming soon','ছবি শিগগিরই যোগ হবে','General','placeholder',true,6)
on conflict(slug) do update set title_en=excluded.title_en,title_bn=excluded.title_bn,summary_en=excluded.summary_en,summary_bn=excluded.summary_bn,alt_en=excluded.alt_en,alt_bn=excluded.alt_bn,caption_en=excluded.caption_en,caption_bn=excluded.caption_bn,category=excluded.category,status=excluded.status,published=excluded.published,sort_order=excluded.sort_order;

-- Partners are intentionally not seeded. Add only verified relationships.
