'use server';
import{randomUUID}from"node:crypto";import{revalidatePath}from"next/cache";import{z}from"zod";import{requireAdmin}from"@/lib/admin/auth";
const tables=["projects","apps","gallery_items","news_articles","founder_profiles","achievements","timeline_events","partners","resources","contact_messages"]as const;const tableSchema=z.enum(tables),idSchema=z.string().uuid();
const optionalText=(max:number)=>z.string().trim().max(max).optional();const optionalUrl=z.string().url().or(z.literal("")).optional();
const recordSchema=z.object({id:z.string().uuid().optional(),slug:optionalText(120),title_en:optionalText(200),title_bn:optionalText(200),summary_en:optionalText(1000),summary_bn:optionalText(1000),content_en:optionalText(20000),content_bn:optionalText(20000),status:optionalText(50),category:optionalText(100),year:z.coerce.number().int().min(1900).max(2200).nullable().optional(),sort_order:z.coerce.number().int().min(-10000).max(10000).optional(),published:z.boolean().optional(),featured:z.boolean().optional(),image_url:optionalUrl,name:optionalText(200),author:optionalText(200),platform:optionalText(100),play_store_url:optionalUrl,website_url:optionalUrl,file_url:optionalUrl,external_url:optionalUrl,thumbnail_url:optionalUrl,alt_en:optionalText(300),alt_bn:optionalText(300),caption_en:optionalText(500),caption_bn:optionalText(500),seo_title:optionalText(200),seo_description:optionalText(500),event_date:optionalText(20)}).strict();
export type AdminResult={ok:boolean;message:string};const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,120);
export async function saveContent(tableInput:string,input:unknown):Promise<AdminResult>{try{const table=tableSchema.parse(tableInput),data=recordSchema.parse(input),{db}=await requireAdmin();if(table!=="contact_messages"){data.slug=slugify(data.slug||data.title_en||data.name||"");if(!data.slug||!data.title_en)return{ok:false,message:"English title and a valid slug are required."}}const id=data.id;delete data.id;const{error}=await(id?db.from(table).update(data).eq("id",id):db.from(table).insert(data));if(error)return{ok:false,message:"The record could not be saved. Check required and unique fields."};revalidatePath("/");revalidatePath(`/admin/${table.replace("_articles","").replace("_items","").replace("_events","timeline")}`);return{ok:true,message:id?"Changes saved.":"Content created."}}catch(error){return{ok:false,message:error instanceof z.ZodError?"Please correct the highlighted form fields.":"You are not authorized to perform this action."}}}
export async function deleteContent(tableInput:string,idInput:string,imagePath?:string):Promise<AdminResult>{try{const table=tableSchema.parse(tableInput),id=idSchema.parse(idInput),{db}=await requireAdmin();if(imagePath){const media=await deleteMedia(imagePath);if(!media.ok)return media}const{error}=await db.from(table).delete().eq("id",id);if(error)return{ok:false,message:"Delete failed."};revalidatePath("/");return{ok:true,message:"Content deleted."}}catch{return{ok:false,message:"You are not authorized to delete this item."}}}
export async function toggleContent(tableInput:string,idInput:string,field:"published"|"featured",value:boolean):Promise<AdminResult>{try{const table=tableSchema.parse(tableInput),id=idSchema.parse(idInput),{db}=await requireAdmin(),{error}=await db.from(table).update({[field]:value}).eq("id",id);if(error)return{ok:false,message:"Update failed."};revalidatePath("/");return{ok:true,message:field==="published"?(value?"Content published.":"Content moved to draft."):(value?"Content featured.":"Feature removed.")}}catch{return{ok:false,message:"Unauthorized update."}}}
const folders=["projects","apps","gallery","news","founder","partners","achievements"]as const;const signatures={"image/jpeg":(b:Uint8Array)=>b[0]===0xff&&b[1]===0xd8&&b[2]===0xff,"image/png":(b:Uint8Array)=>[0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a].every((v,i)=>b[i]===v),"image/webp":(b:Uint8Array)=>String.fromCharCode(...b.slice(0,4))==="RIFF"&&String.fromCharCode(...b.slice(8,12))==="WEBP"};
export async function uploadMedia(formData:FormData):Promise<{ok:boolean;message:string;url?:string;path?:string}>{try{const folder=z.enum(folders).parse(formData.get("folder")),file=formData.get("file");if(!(file instanceof File))return{ok:false,message:"Choose an image."};if(!(file.type in signatures))return{ok:false,message:"Only JPEG, PNG and WebP are allowed."};if(file.size<=0||file.size>5*1024*1024)return{ok:false,message:"Image must be 5 MB or smaller."};const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer()),valid=signatures[file.type as keyof typeof signatures](bytes);if(!valid)return{ok:false,message:"File contents do not match the selected image type."};const ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"}[file.type],path=`${folder}/${randomUUID()}.${ext}`,{db}=await requireAdmin(),{error}=await db.storage.from("rit-media").upload(path,file,{contentType:file.type,upsert:false});if(error)return{ok:false,message:"Upload failed."};return{ok:true,message:"Image uploaded.",path,url:db.storage.from("rit-media").getPublicUrl(path).data.publicUrl}}catch{return{ok:false,message:"Unauthorized upload or invalid image."}}}
export async function deleteMedia(path:string):Promise<AdminResult>{try{if(!/^(projects|apps|gallery|news|founder|partners|achievements)\/[a-f0-9-]+\.(jpg|png|webp)$/.test(path))return{ok:false,message:"Invalid media path."};const{db}=await requireAdmin(),{error}=await db.storage.from("rit-media").remove([path]);return error?{ok:false,message:"Image deletion failed."}:{ok:true,message:"Image removed."}}catch{return{ok:false,message:"Unauthorized image deletion."}}}
