'use client';

import { useEffect, useState } from "react";
import Logo from "./Logo";
import HeroSection from "./HeroSection";
import AboutSection from "./AboutSection";
import DivisionSection from "./DivisionSection";
import ProjectsSection from "./ProjectsSection";
import AppsSection from "./AppsSection";
import StatsSection from "./StatsSection";
import GallerySection from "./GallerySection";
import FounderSection from "./FounderSection";
import NewsSection from "./NewsSection";
import ContactSection from "./ContactSection";
import Footer from "./Footer";

export type SiteText = { nav:string[]; heroA:string; heroB:string; heroText:string; about:string; aboutText:string; divisions:string; projects:string; apps:string; news:string; founder:string; founderText:string; contact:string; send:string; success:string; explore:string; talk:string };
const copy: Record<"en"|"bn",SiteText>={en:{nav:["Home","About","Divisions","Projects","Apps","News","Founder","Contact"],heroA:"Practical innovation",heroB:"for a better future",heroText:"We unite agriculture, engineering, software and research to turn real-world challenges into useful solutions.",about:"Built for progress. Grounded in purpose.",aboutText:"RIT is a multidisciplinary innovation company from Bangladesh, developing dependable technology that helps people and businesses move forward.",divisions:"Core Divisions",projects:"Featured Projects",apps:"Digital products for everyday progress",news:"News & Insights",founder:"Founder & Leadership",founderText:"Md. Rasel Ahmed is building RIT around a simple belief: practical ideas, carefully developed, can create meaningful progress.",contact:"Start a conversation",send:"Send message",success:"Thank you — your message has been received.",explore:"Explore RIT",talk:"Talk to us"},bn:{nav:["হোম","পরিচিতি","বিভাগ","প্রকল্প","অ্যাপস","সংবাদ","প্রতিষ্ঠাতা","যোগাযোগ"],heroA:"বাস্তবমুখী উদ্ভাবন",heroB:"উন্নত আগামীর জন্য",heroText:"আমরা কৃষি, প্রকৌশল, সফটওয়্যার ও গবেষণাকে একত্র করে বাস্তব সমস্যার কার্যকর সমাধান তৈরি করি।",about:"অগ্রগতির জন্য নির্মিত, উদ্দেশ্যে অবিচল।",aboutText:"RIT বাংলাদেশের একটি বহুমুখী উদ্ভাবনী প্রতিষ্ঠান, যা মানুষ ও ব্যবসার অগ্রগতির জন্য নির্ভরযোগ্য প্রযুক্তি তৈরি করছে।",divisions:"মূল বিভাগসমূহ",projects:"নির্বাচিত প্রকল্প",apps:"প্রতিদিনের অগ্রগতির ডিজিটাল পণ্য",news:"সংবাদ ও অন্তর্দৃষ্টি",founder:"প্রতিষ্ঠাতা ও নেতৃত্ব",founderText:"মো. রাসেল আহমেদ একটি সহজ বিশ্বাসে RIT গড়ছেন।",contact:"আলোচনা শুরু করুন",send:"বার্তা পাঠান",success:"ধন্যবাদ — আপনার বার্তা গ্রহণ করা হয়েছে।",explore:"RIT সম্পর্কে জানুন",talk:"যোগাযোগ করুন"}};
export default function SiteClient(){const [lang,setLang]=useState<"en"|"bn">("en"),[dark,setDark]=useState(false),[menu,setMenu]=useState(false);const t=copy[lang],ids=["home","about","divisions","projects","apps","news","founder","contact"];useEffect(()=>{const saved=localStorage.getItem("rit-lang");if(saved==="en"||saved==="bn")setLang(saved);setDark(localStorage.getItem("rit-theme")==="dark");},[]);useEffect(()=>{document.body.classList.toggle("dark",dark);localStorage.setItem("rit-lang",lang);localStorage.setItem("rit-theme",dark?"dark":"light");},[lang,dark]);return <><header className="header"><div className="container nav"><a href="#home"><Logo/></a><button className="menuBtn" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?"open":""}>{ids.map((id,i)=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{t.nav[i]}</a>)}<button className="utility" onClick={()=>setLang(lang==="en"?"bn":"en")}>{lang==="en"?"বাংলা":"EN"}</button><button className="utility" aria-label="Toggle dark mode" onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button></nav></div></header><main><HeroSection text={t}/><AboutSection text={t}/><DivisionSection text={t}/><ProjectsSection text={t}/><AppsSection text={t}/><StatsSection/><GallerySection/><NewsSection text={t}/><FounderSection text={t}/><ContactSection text={t}/></main><a className="whatsapp" href="https://wa.me/8801000000000" target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp">◔</a><Footer/></>}
