export const divisions = [
  { slug: "agricultural-engineering", titleEn: "Agricultural Engineering", titleBn: "কৃষি প্রকৌশল", summaryEn: "Practical machinery concepts and engineering support for agricultural workflows.", summaryBn: "কৃষিকাজের জন্য বাস্তবমুখী যন্ত্র ধারণা ও প্রকৌশল সহায়তা।" },
  { slug: "software-digital", titleEn: "Software & Digital Products", titleBn: "সফটওয়্যার ও ডিজিটাল পণ্য", summaryEn: "Focused software and mobile products designed around real user needs.", summaryBn: "বাস্তব ব্যবহারকারীর প্রয়োজনভিত্তিক সফটওয়্যার ও মোবাইল পণ্য।" },
  { slug: "research-innovation", titleEn: "Research & Innovation", titleBn: "গবেষণা ও উদ্ভাবন", summaryEn: "Structured investigation, experimentation and responsible improvement.", summaryBn: "পরিকল্পিত অনুসন্ধান, পরীক্ষা ও দায়িত্বশীল উন্নয়ন।" },
  { slug: "design-prototyping", titleEn: "Design & Prototyping", titleBn: "নকশা ও প্রোটোটাইপিং", summaryEn: "From early technical concepts to testable prototypes and documentation.", summaryBn: "প্রাথমিক কারিগরি ধারণা থেকে পরীক্ষাযোগ্য প্রোটোটাইপ ও নথি।" },
] as const;
export const services = [
  { slug: "agricultural-machinery-design", titleEn: "Agricultural Machinery Design", titleBn: "কৃষিযন্ত্র নকশা", summaryEn: "Concept development and design support for practical agricultural machinery.", summaryBn: "ব্যবহারিক কৃষিযন্ত্রের ধারণা উন্নয়ন ও নকশা সহায়তা।", audienceEn: "Farm-focused teams and agricultural initiatives", audienceBn: "কৃষিকেন্দ্রিক দল ও উদ্যোগ" },
  { slug: "product-development", titleEn: "Product Development", titleBn: "পণ্য উন্নয়ন", summaryEn: "A structured path from problem definition to documented prototype.", summaryBn: "সমস্যা নির্ধারণ থেকে নথিভুক্ত প্রোটোটাইপ পর্যন্ত পরিকল্পিত প্রক্রিয়া।", audienceEn: "Early-stage products and innovation teams", audienceBn: "প্রাথমিক পর্যায়ের পণ্য ও উদ্ভাবনী দল" },
  { slug: "software-development", titleEn: "Software Development", titleBn: "সফটওয়্যার উন্নয়ন", summaryEn: "Purpose-built web tools and business software with maintainable foundations.", summaryBn: "রক্ষণাবেক্ষণযোগ্য ভিত্তিতে ওয়েব টুল ও ব্যবসায়িক সফটওয়্যার।", audienceEn: "Organizations with defined digital workflows", audienceBn: "সুনির্দিষ্ট ডিজিটাল কার্যপ্রবাহের প্রতিষ্ঠান" },
  { slug: "mobile-app-development", titleEn: "Mobile Application Development", titleBn: "মোবাইল অ্যাপ উন্নয়ন", summaryEn: "Accessible mobile experiences for local and specialized use cases.", summaryBn: "স্থানীয় ও বিশেষায়িত ব্যবহারের জন্য সহজলভ্য মোবাইল অভিজ্ঞতা।", audienceEn: "Education, agriculture and utility products", audienceBn: "শিক্ষা, কৃষি ও ইউটিলিটি পণ্য" },
  { slug: "technical-documentation", titleEn: "Technical Documentation", titleBn: "কারিগরি নথি", summaryEn: "Clear product, process and engineering documentation.", summaryBn: "পরিষ্কার পণ্য, প্রক্রিয়া ও প্রকৌশল নথি।", audienceEn: "Product and engineering teams", audienceBn: "পণ্য ও প্রকৌশল দল" },
  { slug: "research-support", titleEn: "Research Support", titleBn: "গবেষণা সহায়তা", summaryEn: "Problem framing, evidence organization and prototype planning support.", summaryBn: "সমস্যা বিন্যাস, তথ্য সংগঠন ও প্রোটোটাইপ পরিকল্পনা সহায়তা।", audienceEn: "Researchers and development initiatives", audienceBn: "গবেষক ও উন্নয়ন উদ্যোগ" },
  { slug: "consultation", titleEn: "Technical Consultation", titleBn: "কারিগরি পরামর্শ", summaryEn: "An initial technical review to clarify scope, constraints and next steps.", summaryBn: "পরিধি, সীমাবদ্ধতা ও পরবর্তী ধাপ স্পষ্ট করতে প্রাথমিক কারিগরি পর্যালোচনা।", audienceEn: "Organizations exploring a practical solution", audienceBn: "বাস্তব সমাধান অনুসন্ধানকারী প্রতিষ্ঠান" },
] as const;
export const processSteps = [["Identify", "চিহ্নিতকরণ"], ["Research", "গবেষণা"], ["Design", "নকশা"], ["Prototype", "প্রোটোটাইপ"], ["Test", "পরীক্ষা"], ["Improve", "উন্নয়ন"], ["Deploy", "প্রয়োগ"]] as const;
